// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerieA.Data;

#nullable disable

namespace SerieA.Migrations
{
    [DbContext(typeof(SerieAContext))]
    partial class SerieAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SerieA.Models.Calciatore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroMaglia")
                        .HasColumnType("int");

                    b.Property<int?>("SquadraId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SquadraId");

                    b.ToTable("Calciatore");
                });

            modelBuilder.Entity("SerieA.Models.Campionato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<string>("Nazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCampionato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campionato");
                });

            modelBuilder.Entity("SerieA.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Anno")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CampionatoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampionatoId");

                    b.ToTable("Squadra");
                });

            modelBuilder.Entity("SerieA.Models.Calciatore", b =>
                {
                    b.HasOne("SerieA.Models.Squadra", "Squadra")
                        .WithMany("Calciatori")
                        .HasForeignKey("SquadraId");

                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("SerieA.Models.Squadra", b =>
                {
                    b.HasOne("SerieA.Models.Campionato", "Campionato")
                        .WithMany("Squadra")
                        .HasForeignKey("CampionatoId");

                    b.Navigation("Campionato");
                });

            modelBuilder.Entity("SerieA.Models.Campionato", b =>
                {
                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("SerieA.Models.Squadra", b =>
                {
                    b.Navigation("Calciatori");
                });
#pragma warning restore 612, 618
        }
    }
}
